module.exports.TEST_TREE = {
  'basic' : {
    'all' : false,
    '#1' : false,
    '#2' : false,
    '#3' : false,
  },
  'ipc' :{
    'all' : false,
    '#1' : false,
    '#2' : false,
    '#3' : false,
    '#4': false,
  },
  'coverage' :{
    'all' : false,
    '#1' : false,
    '#2' : false,
    '#3' : false,
  },
  'cache' :{
    'all' : false,
    '#1' : false
  },
  'ethereum' : {
    'all' : false,
    '#1' : false,
    '#2' : false,
    '#3' : false,
    '#4' : false,
    '#5' : false,
  },
  'task_manager' :{
    'all' : false,
    '#1' : false,
    '#2' : false,
    '#3' : false,
    '#4' : false,
    '#5' : false,
  },
  'task_flow' : {
    'all' :false,
    '#1' : false,
  },
  'sync_basic':{
    'all' : false,
    '#1' : false,
    '#2' : false,
    '#3' : false,
    '#4' : false,
    '#5' : false,
  },
  'sync_network':{
    'all' : false,
    '#1' : false,
  },
  'jsonrpc_basic':{
    'all' : false,
    '#1' : false,
    '#2' : false,
    '#3' : false,
    '#4' : false,
    '#5' : false,
    '#6' : false,
    '#7' : true,
  },
  'jsonrpc_advanced' :{
    'all' : true,
    '#1' : true,
    '#2' : true,
  },
  'actions_tests':{
    'all' : false,
    '#1' : false,
    '#2' : false,
    '#3' : false,
  },
  'principal' : {
    'all' : false,
    '#1' : false,
    '#2' : false,
  },
  'verifier':{
    'all' : false,
    '#1' : false,
    '#2' : false,
    '#3' : false,
    '#4' : false,
    '#5' : false,
    '#6' : false,
    '#7' : false,
    '#8' : false,
    '#9' : false,
    '#10' : false,
    '#11' : false,
    '#12' : false,
    '#13' : false,
    '#14' : false,
    '#15' : false,
    '#16' : false,
    '#17' : false,
    '#18' : false,
    '#19' : false,
    '#20' : false,
    '#21' : false,
    '#22' : false,
    '#23' : false,
    '#24' : false,
    '#25' : false,
    '#26' : false,
    '#27' : false,
    '#28' : false,
  }
};


