module.exports.TEST_TREE = {
  'basic' : {
    'all' : true,
    '#1' : true,
    '#2' : true,
    '#3' : true,
  },
  'ipc' :{
    'all' : true,
    '#1' : true,
    '#2' : true,
    '#3' : true,
    '#4': true,
    '#5': true,
    '#6': true,
  },
  'coverage' :{
    'all' : true,
    '#1' : true,
  },
  'cache' :{
    'all' : true,
    '#1' : true
  },
  'ethereum' : {
    'all' : true,
    '#1' : true,
    '#2' : true,
    '#3' : true,
    '#4' : true,
    '#5' : true,
    '#6' : true,
  },
  'task_manager' :{
    'all' : true,
    '#1' : true,
    '#2' : true,
    '#3' : true,
    '#4' : true,
    '#5' : true,
    '#6' : true,
  },
  'task_flow' : {
    'all' :true,
    '#1' : true,
    '#2' : true,
    '#3' : true,
    '#4' : true,
  },
  'sync_basic':{
    'all' : true,
    '#1' : true,
    '#2' : true,
    '#3' : true,
    '#4' : true,
    '#5' : true,
  },
  'sync_network':{
    'all' : true,
    '#1' : true,
  },
  'jsonrpc_basic':{
    'all' : true,
    '#1' : true,
    '#2' : true,
    '#3' : true,
    '#4' : true,
    '#5' : true,
    '#6' : true,
  },
  'jsonrpc_advanced' :{
    'all' : true,
    '#1' : true,
    '#2' : true,
    '#3' : true,
    '#4' : true,
  },
  'actions_tests':{
    'all' : true,
    '#1' : true,
    '#2' : true,
    '#3' : true,
  },
  'principal' : {
    'all' : true,
    '#1' : true,
    '#2' : true,
    '#3' : true,
  },
  'verifier':{
    'all' : true,
    '#1' : true,
    '#2' : true,
    '#3' : true,
    '#4' : true,
    '#5' : true,
    '#6' : true,
    '#7' : true,
    '#8' : true,
    '#9' : true,
    '#10' : true,
    '#11' : true,
    '#12' : true,
    '#13' : true,
    '#14' : true,
    '#15' : true,
    '#16' : true,
    '#17' : true,
    '#18' : true,
    '#19' : true,
    '#20' : true,
    '#21' : true,
    '#22' : true,
    '#23' : true,
    '#24' : true,
    '#25' : true,
    '#26' : true,
    '#27' : true,
    '#28' : true,
    '#29' : true,
    '#30' : true,
    '#31' : true,
    '#32' : true,
    '#33' : true,
    '#34' : true,
    '#35' : true,
    '#36' : true,
    '#37' : true,
    '#38' : true,
    '#39' : true,
    '#40' : true,
    '#41' : true,
    '#42' : true,
    '#43' : true,
    '#44' : true,
    '#45' : true,
    '#46' : true,
    '#47' : true,
  },
  'ethereum_integration':{
    'all' : true,
    '#1' : true,
    '#2' : true,
    '#3' : true,
    '#4' : true,
    '#5' : true,
    '#6' : true,
    '#7' : true,
    '#8' : true,
  },
  'single_config':{
    'all' : true,
    '#1' : true,
    '#2' : true,
  },
  'init_worker' : {
    'all' : true,
    '#1' : true,
  },
};


