module.exports.TEST_TREE = {
  'basic' : {
    'all' : false,
    '#1' : true,
    '#2' : true,
    '#3' : true,
  },
  'ipc' :{
    'all' : false,
    '#1' : true,
    '#2' : true,
    '#3' : true,
    '#4': true,
  },
  'coverage' :{
    'all' : false,
    '#1' : true,
    '#2' : true,
    '#3' : true,
  },
  'cache' :{
    'all' : true,
    '#1' : true
  },
  'ethereum' : {
    'all' : false,
    '#1' : true,
    '#2' : true,
    '#3' : true,
    '#4' : true,
    '#5' : true,
  },
  'task_manager' :{
    'all' : false,
    '#1' : true,
    '#2' : true,
    '#3' : true,
    '#4' : true,
    '#5' : true,
  },
  'task_flow' : {
    'all' :false,
    '#1' : true,
  },
  'sync_basic':{
    'all' : false,
    '#1' : true,
    '#2' : true,
    '#3' : true,
    '#4' : true,
    '#5' : true,
  },
  'sync_network':{
    'all' : true,
    '#1' : true,
  },
  'jsonrpc_basic':{
    'all' : false,
    '#1' : true,
    '#2' : true,
    '#3' : true,
    '#4' : true,
    '#5' : true,
    '#6' : true,
  },
  'actions_tests':{
    'all' : false,
    '#1' : true,
    '#2' : true,
    '#3' : true,
  },
  'principal' : {
    'all' : false,
    '#1' : true,
    '#2' : true,
  },
  'verifier':{
    'all' : false,
    '#1' : true,
    '#2' : true,
    '#3' : true,
    '#4' : true,
    '#5' : true,
    '#6' : true,
    '#7' : true,
    '#8' : true,
    '#9' : true,
    '#10' : true,
    '#11' : true,
    '#12' : true,
    '#13' : true,
    '#14' : true,
    '#15' : true,
    '#16' : true,
    '#17' : true,
    '#18' : true,
    '#19' : true,
    '#20' : true,
    '#21' : true,
    '#22' : true,
    '#23' : true,
    '#24' : true,
    '#25' : true,
    '#26' : true,
    '#27' : true,
    '#28' : true,
  }
};


